### ISSUE TITLE
Not working for VS Code 1.94

### ISSUE THREAD

**Issue by crohde7707** [rolandostar/tabletopsimulator-lua-vscode#48]
Looks like when my VS code updated to 1.94, the scripts for the extension stopped working, giving this
![image](https://github.com/user-attachments/assets/a7e1c780-662c-4460-9d41-161afd2f823e)

**Comment by chrislavoy** [comment]
I get this error from Extension Host when trying to run `Get Lua Scripts`.
```
2024-10-10 08:57:38.583 [info] ExtensionService#_doActivateExtension rolandostar.tabletopsimulator-lua, startup: false, activationEvent: 'onCommand:ttslua.getScripts'
2024-10-10 08:57:38.605 [error] Activating extension rolandostar.tabletopsimulator-lua failed due to an error:
2024-10-10 08:57:38.605 [error] Error: ENOENT, vscode-oniguruma\release\onig.wasm not found in c:\Users\chris\AppData\Local\Programs\Microsoft VS Code\resources\app\node_modules.asar
	at createError (node:electron/js2c/node_init:2:1657)
	at t.readFileSync (node:electron/js2c/node_init:2:10070)
	at 829 (c:\Users\chris\.vscode\extensions\rolandostar.tabletopsimulator-lua-1.1.3\dist\extension.js:9406:20)
	at __webpack_require__ (c:\Users\chris\.vscode\extensions\rolandostar.tabletopsimulator-lua-1.1.3\dist\extension.js:9517:42)
	at 603 (c:\Users\chris\.vscode\extensions\rolandostar.tabletopsimulator-lua-1.1.3\dist\extension.js:4191:20)
	at __webpack_require__ (c:\Users\chris\.vscode\extensions\rolandostar.tabletopsimulator-lua-1.1.3\dist\extension.js:9517:42)
	at 112 (c:\Users\chris\.vscode\extensions\rolandostar.tabletopsimulator-lua-1.1.3\dist\extension.js:4027:22)
	at __webpack_require__ (c:\Users\chris\.vscode\extensions\rolandostar.tabletopsimulator-lua-1.1.3\dist\extension.js:9517:42)
	at c:\Users\chris\.vscode\extensions\rolandostar.tabletopsimulator-lua-1.1.3\dist\extension.js:9540:18
	at Object.<anonymous> (c:\Users\chris\.vscode\extensions\rolandostar.tabletopsimulator-lua-1.1.3\dist\extension.js:9541:12)
	at Module._compile (node:internal/modules/cjs/loader:1373:14)
	at Module._extensions..js (node:internal/modules/cjs/loader:1432:10)
	at Module.load (node:internal/modules/cjs/loader:1215:32)
	at Module._load (node:internal/modules/cjs/loader:1031:12)
	at c._load (node:electron/js2c/node_init:2:13801)
	at e._load (file:///c:/Users/chris/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:174:10870)
	at t._load (file:///c:/Users/chris/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:166:22422)
	at i._load (file:///c:/Users/chris/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:158:4651)
	at Module.require (node:internal/modules/cjs/loader:1240:19)
	at require (node:internal/modules/helpers:179:18)
	at hB.xb (file:///c:/Users/chris/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:166:23767)
	at async Promise.all (index 0)
```

**Comment by androvisuals** [comment]
Same here

**Comment by cmaggard** [comment]
To get unblocked, edit `%HOME%\.vscode\extensions\rolandostar.tabletopsimulator-lua-1.1.3\dist\extension.js` and on line 9406, change `node_modules.asar` to `node_modules`.

**Comment by Zwrap** [comment]
> To get unblocked, edit `%HOME%\.vscode\extensions\rolandostar.tabletopsimulator-lua-1.1.3\dist\extension.js` and on line 9406, change `node_modules.asar` to `node_modules`.

that work. do you know why?

**Comment by androvisuals** [comment]
@cmaggard Thanks a million for this fix. Really appreciate it!

**Comment by poiskim** [comment]
@cmaggard i really appreciate you so much

**Comment by HPC2H2** [comment]
@cmaggard Thank you. You're a doll!

**Comment by TheUntamed** [comment]
Sadly this did not work for me. Any other solution? (I'm running the latest vs Code version 1.102.2 on Windows 10)

**Comment by Zwrap** [comment]
> Sadly this did not work for me. Any other solution? (I'm running the latest vs Code version 1.102.2 on Windows 10)

You could manually copy the script from tabletop simulator then paste into vscode, then copy and paste it back into tabletop simulator.  If the extension won't work.

**Comment by ShaunsWork** [comment]
Hi I've published an updated extension that should handle any more changes to this particular issue on my page.
https://github.com/ShaunsWork/tabletopsimulator-lua-community/releases/tag/v1.1.6
Just download the tabletopsimulator-lua-community-1.1.6.vsix and install the extension via that.

**Comment by bcsj** [comment]
I had this issue and applied the fix suggested by @cmaggard a while back and it worked great. Recently the issue reappeared (the fix was still in place) and I found that undoing the fix again worked for me this time, unsure about why.

**Comment by jessicabalu** [comment]
I encountered this issue for the first time today, and I had "node_modules" in the js so I changed it to "node_modules.asar" and that worked for me for some reason
